import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";

import { Sorts_Mill_Goudy } from 'next/font/google'
import { Toaster } from "@/components/ui/sonner";
import { VisualizerProvider } from "./context/visualizer";
import { LanguageProvider } from "./context/changeLanguage";

const Sorts = Sorts_Mill_Goudy({
  variable: "--font-Sorts-Mill",
  weight: "400"
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${Sorts.variable} antialiased portBody`}
      >
          <div className="mainContainer">
        <VisualizerProvider>
        <LanguageProvider>
            <Header />
            {children}
            <Toaster />
        </LanguageProvider>
        </VisualizerProvider>
          </div>
      </body>
    </html>
  );
}
